apiVersion: v1
kind: Service
metadata:
  name: sleepy-workload-service
spec:
  selector:
    app: sleepy-workload
  ports:
  - name: sleepy-workload-service-port
    protocol: TCP
    port: 80
    targetPort: sleepy-workload-http-port